### ISSUE TITLE
hardcoded selectors

### ISSUE THREAD

**Issue by ali-farhad** [silvestrodecaro/microsoft-account-creator#1]
I am not sure if you know this, but all your selectors are hardcoded with the classes name. these atomic classes name which you are using to find certain elements and click on them, these classes are not same across everybody's computer. they can change depending on various factors. 

right now the script even can't get past google.com.

**Comment by V1NAY007** [comment]
Same Problem

**Comment by L-Goncalves** [comment]
Same, I might try to re-adapt this script to work dinamically.

**Comment by silvestrodecaro** [comment]
Hi guys, thank you for your help with the bot, and I apologize for abandoning it for a couple of months. I had time to take a quick look at it and fix any problems that were there
