### ISSUE TITLE
captcha is hard

### ISSUE THREAD

**Issue by TuvaBilisim** [silvestrodecaro/microsoft-account-creator#17]
In the past, simple captcha would come. But now I have at least 10 captchas to solve. and the hardest part... 
I connected via mobile data, still the same, I used VPN, still the same. I wonder why?
chrome latest version.
![ekrannnn](https://github.com/user-attachments/assets/2c829e67-563b-4ac6-bd27-d4b3c8406078)

**Comment by silvestrodecaro** [comment]
try deleting data folder and restart

**Comment by TuvaBilisim** [comment]
Thank you for your answer. I did what you said. but nothing changed. I tried from different ips. I deleted the program and reinstalled it. While captchas were very easy before, now they are always difficult. I wonder what am I doing wrong? I have 2 computers. The result is the same in both.

**Comment by TuvaBilisim** [comment]
Thank you for your answer. I did what you said. but nothing changed. I tried from different ips. I deleted the program and reinstalled it. While captchas were very easy before, now they are always difficult. I wonder what am I doing wrong? I have 2 computers. The result is the same in both.
