### ISSUE TITLE
Stuck at Solving Captcha

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [silvestrodecaro/microsoft-account-creator#18]
After i solve the captcha, it wont continue. i believe it cant detect the selector

**Comment by silvestrodecaro** [comment]
I just tested it and didn’t encounter any issues. Please try again, and if the problem persists, send some screenshots or provide more details.

**Comment by TOBIBLASTER00912** [comment]
ima clone the source one more time and try again, if it still wont work i can record a video

**Comment by silvestrodecaro** [comment]
any news?

**Comment by torturado** [comment]
The captchas are so hard and so long for me. I don't even have time to solve them.
![image](https://github.com/user-attachments/assets/b30361ca-2644-4b08-ae19-57aae6a2fffa)

**Comment by silvestrodecaro** [comment]
If the captchas are excessively difficult or too frequent, don't bother solving them. In any case, the account will likely be of low quality due to **evident issues with the IP, browser, or fingerprint**. I just tested the bot and encountered no problems with captchas
