### ISSUE TITLE
captchas are very difficult

### ISSUE THREAD

**Issue by TuvaBilisim** [silvestrodecaro/microsoft-account-creator#19]
captchas are really hard. I clear all data on the computer. I even delete temp - recent and reinstall the program. I'm changing the rope. But every time the most difficult captchas with 15 solutions appear. I try it on 2 different computers, but the result is the same. I can't fix it. I've been trying for 2-3 weeks. what should we do?

[
![captcha](https://github.com/user-attachments/assets/5b95b830-a4e6-4c41-b629-4b95cb97ba4a)
](url)

**Comment by krais006** [comment]
I have the same problem, everything worked fine, but now even on MOBILE PROXY I have the highest captche after 10-15 choices... I think they detect it somehow by the device, have you checked it on another PC?

**Comment by krais006** [comment]
so you checked two different computers, it doesn't work for me either

**Comment by newqnes** [comment]
If you want a fully comprehensive bot, I can help. Feel free to message me on Discord.:newqne

**Comment by silvestrodecaro** [comment]
If the captchas are excessively difficult or too frequent, don't bother solving them. In any case, the account will likely be of low quality due to **evident issues with the IP, browser, or fingerprint**. I just tested the bot and encountered no problems with captchas
