### ISSUE TITLE
TypeError: browser.createIncognitoBrowserContext is not a function

### ISSUE THREAD

**Issue by Filipinator** [silvestrodecaro/microsoft-account-creator#4]
I got this error:
C:\Users\xxxxx\Desktop\microsoft-account-creator-main\app.js:24
    const context = await browser.createIncognitoBrowserContext();
                                  ^

TypeError: browser.createIncognitoBrowserContext is not a function
    at start (C:\Users\xxxxx\Desktop\microsoft-account-creator-main\app.js:24:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

**Comment by oibarracdev** [comment]
same here

**Comment by Filipinator** [comment]
I just deleted it downloaded it again and it works now. Idk why was that.

**Comment by silvestrodecaro** [comment]
Puppeteer is having problems due to breaking changes, that because the browser context has been renamed in the latest version of the puppeteer package. Try removing node modules and reinstalling the package
