### ISSUE TITLE
Adding / Authorizing Recovery Email

### ISSUE THREAD

**Issue by sujay1599** [silvestrodecaro/microsoft-account-creator#7]
Once the account is created, would you be able to use the last created login and adda primary recovery email so the account does not get deleted? 

I am trying to figure that out.

The accounts stay active for a bout a day before deletion. 

Good work lmk,
CJ

**Comment by silvestrodecaro** [comment]
Check the latest update and let me know :)

**Comment by sujay1599** [comment]
:) 

ur code helped me build my seedr.cc torrent bot!

Thank you!

**Comment by sujay1599** [comment]
can we customize the recovery address being used?!

**Comment by silvestrodecaro** [comment]
I'm glad the update helped you. What exactly do you mean by "customize"?

**Comment by sujay1599** [comment]
Allow me to input my own recovery email.

**Comment by silvestrodecaro** [comment]
sure, remove the script I implemented (recMail.js), insert the email as a string in the RecoveryEmail constant and remove the automatic part about inserting the code

**Comment by sujay1599** [comment]
will try!
